# Generated by Django 3.2.4 on 2021-07-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('main_photo', models.ImageField(upload_to='', verbose_name='Главное фото')),
            ],
        ),
        migrations.CreateModel(
            name='News_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.news')),
            ],
        ),
        migrations.CreateModel(
            name='News_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.news')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='Pages_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.pages')),
            ],
        ),
        migrations.CreateModel(
            name='Pages_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.pages')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('connecting_to_news', models.ManyToManyField(through='tigers.News_Photos', to='tigers.News')),
                ('connecting_to_pages', models.ManyToManyField(through='tigers.Pages_Photos', to='tigers.Pages')),
            ],
        ),
        migrations.CreateModel(
            name='Photosets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('video', models.CharField(max_length=250, verbose_name='Видео')),
                ('connecting_to_news', models.ManyToManyField(through='tigers.News_Videos', to='tigers.News')),
                ('connecting_to_pages', models.ManyToManyField(through='tigers.Pages_Videos', to='tigers.Pages')),
            ],
        ),
        migrations.CreateModel(
            name='Photosets_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.photos')),
                ('photoset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.photosets')),
            ],
        ),
        migrations.AddField(
            model_name='photosets',
            name='connecting_to_photos',
            field=models.ManyToManyField(through='tigers.Photosets_Photos', to='tigers.Photos'),
        ),
        migrations.AddField(
            model_name='pages_videos',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.videos'),
        ),
        migrations.AddField(
            model_name='pages_photos',
            name='photo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.photos'),
        ),
        migrations.AddField(
            model_name='news_videos',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.videos'),
        ),
        migrations.AddField(
            model_name='news_photos',
            name='photo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tigers.photos'),
        ),
    ]
