# Generated by Django 3.2.4 on 2021-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_photo', models.CharField(max_length=250, verbose_name='Маленькое фото')),
                ('photo', models.CharField(max_length=250, verbose_name='Фото')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=250, verbose_name='Фото')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('video', models.CharField(max_length=250, verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='Photosets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('title_photo', models.CharField(max_length=250, verbose_name='Титульное фото')),
                ('connecting_to_photos', models.ManyToManyField(to='tigers.Photos')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Статья')),
                ('connecting_to_photos', models.ManyToManyField(to='tigers.Photos')),
                ('connecting_to_videos', models.ManyToManyField(to='tigers.Videos')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('photo', models.CharField(max_length=250, verbose_name='Главное фото')),
                ('connecting_to_photos', models.ManyToManyField(to='tigers.Photos')),
                ('connecting_to_videos', models.ManyToManyField(to='tigers.Videos')),
            ],
        ),
    ]
