# Generated by Django 3.2.4 on 2021-07-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigers', '0002_auto_20210728_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
