# Generated by Django 3.2.4 on 2021-07-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigers', '0003_alter_pages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photosets',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.CharField(max_length=240, verbose_name='Видео'),
        ),
    ]
