# Generated by Django 3.2.4 on 2021-07-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigers', '0005_auto_20210728_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.CharField(max_length=250, verbose_name='Фото'),
        ),
    ]
