# Generated by Django 3.2.4 on 2021-08-04 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tigers', '0007_auto_20210803_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosets',
            name='title_photo',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Титульное фото'),
            preserve_default=False,
        ),
    ]
