# Generated by Django 3.2.4 on 2021-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigers', '0008_photosets_title_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
