# Generated by Django 3.2.4 on 2021-08-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigers', '0009_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosets',
            name='date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
