# Generated by Django 3.2.4 on 2021-08-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigers', '0010_alter_photosets_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosets',
            name='date',
        ),
    ]
