# Generated by Django 3.2.4 on 2021-08-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigers', '0011_remove_photosets_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='date',
        ),
    ]
